services:
  # postgres
  postgres:
    image: postgres:15
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=task-management
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
